# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StockHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockHelper
  pod 'Moya', '~> 11.0'
  pod 'DeviceKit', '~> 1.3'
  # parse HTML
  pod 'SwiftSoup'
  # UI
  # https://github.com/WangWenzhuang/ZKProgressHUD
  pod 'ZKProgressHUD'
  
  # UI组件库
  # pod 'Eureka'
  
  # Button角标
  # https://github.com/mustafaibrahim989/MIBadgeButton-Swift/tree/master/MIBadgeButton
  
  target 'StockHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
